const VERIFY_CODE_SENT = 2010
const USER_CREATED = 2011
const USER_UPDATED = 2012
const USER_BLOCK_FOR_SUBSCRIPTION = 2013
const USER_BLOCK_FOR_BALANCE = 2014
const USER_BLOCK_FOR_INCOMPLETE = 2015
const USER_BLOCK_DRIVER_FOR_WAITING_FOR_CONFIRMATION = 2016
const USER_BLOCK_BY_ADMIN = 2017
const USER_GET_INFORMATION = 2017
const USER_UNBLOCK_BY_ADMIN = 2019
const USER_TOKEN_AUTHENTICATE = 2020
const SUPER_AGENT_CREATED = 2021
const SUPER_AGENT_LISTED = 2022
const AGENT_CREATED = 2023
const DRIVER_FOUNDED = 2024
const USER_BLOCK_AGENT_FOR_WAITING_FOR_CONFIRMATION = 2025
const PASSENGER_FOUNDED = 2026
const USER_BLOCKED = 2027
const USER_UPDATED_TO_SUPER_AGENT = 2028
const ERROR_UPDATE_USER_TO_AGENT = 2029
const AGENT_DELETED = 2030
const DRIVER_LISTED = 2031
const DRIVER_DELETED = 2032
const WALLET_UPDATED = 2033
const USER_NOT_FOUND = 2034
const DRIVER_CREATED = 2035
const PASSENGER_DELETED = 2036
const PASSENGER_LISTED = 2037
const ERROR_USER_EXIST = 2038
const ERROR_AGENT_ID_AND_DRIVER_ID_NOT_MACH = 2039
const ERROR_TRANSACTION_NOT_FOUND = 2040
const OPERATOR_DELTED = 2041
const UPLOADED_IMAGE = 2042

const REQUEST_OK = 2099

const ERROR_PARAM = 5010
const ERROR_NOT_A_NUMBER = 5011
const ERROR_INVALID_PHONE_NUMBER = 5012
const ERROR_SMS_NOT_SEND = 5013
const ERROR_INVALID_VERIFY_NUMBER = 5014
const ERROR_TOO_MANY_ATTEMPT = 5015
const ERROR_TYPE_NOT_MACH = 5016
const ERROR_TOKEN = 5017
const ERROR_GENDER = 5018
const ERROR_FULL_NAME_MUST_STRING = 5019
const ERROR_WRONG_PARAMETER = 5020
const ERROR_WRONG_UPDATED_FIELDS = 5021
const ERROR_WRONG_BODY_IN_UPDATE_DRIVER_INFORMATION = 5022
const ERROR_WRONG_PARAMETER_IN_PLATE_NUMBER = 5023
const ERROR_WRONG_PARAMETER_IN_VIN = 5024
const ERROR_WRONG_ADDRESS = 5025
const ERROR_WRONG_FINANCIAL_INFORMATION = 5026
const ERROR_IN_USER_UPDATE = 5026
const ERROR_INSUFFICIENT_BALANCE = 5027
const ERROR_AMOUNT_MUST_BE_LARGER_THAN_ZERO = 5028
const ERROR_SUPER_AGENT_EXIST = 5029
const ERROR_AGENT_EXIST = 5030
const ERROR_DRIVER_EXIST = 5031
const ERROR_USER_TYPE_NOT_PERMITTED = 5032
const ERROR_STATUS_UNDEFINED = 5033
const ERROR_INVALID_ID = 5034
const ERROR_AGENT_NOT_FOUND = 5035
const ERROR_SUPER_AGENT_CODE_DUPLICATE = 5036
const ERROR_UPDATE_USER_TO_SUPER_AGENT = 5037
const ERROR_AGENT_CODE_DUPLICATE = 5038
const ERROR_SUPER_AGENT_NOT_FOUND = 5039
const ERROR_TRAVEL_GROUP_NOT_FOUND = 5040
const ERROR_FINANCIAL_GROUP_NOT_FOUND = 5041
const ERROR_DUPLICATE_PHONE_NUMBER = 5042
const ERROR_USER_USE_IN_OTHER_USER = 5043
const ERROR_UPDATE_USER_TO_ADMIN_OPERTATOR = 5044
const ERROR_ADMIN_OPERATOR_EXIST = 5045
const ERROR_PARENT_NOT_FOUND = 5046
const ERROR_USER_TYPE_EXIST = 5047
const ERROR_UPLOAD_FAILD = 5048

const ERROR_REDIS = 5097
const AUTH_FAILED = 5098
const ERROR_INTERNAL = 5099
module.exports = {
  DRIVER_CREATED,
  ERROR_DUPLICATE_PHONE_NUMBER,
  ERROR_TRAVEL_GROUP_NOT_FOUND,
  ERROR_FINANCIAL_GROUP_NOT_FOUND,
  ERROR_UPDATE_USER_TO_SUPER_AGENT,
  USER_BLOCK_FOR_BALANCE,
  ERROR_WRONG_PARAMETER_IN_PLATE_NUMBER,
  ERROR_WRONG_BODY_IN_UPDATE_DRIVER_INFORMATION,
  USER_BLOCK_FOR_SUBSCRIPTION,
  ERROR_WRONG_PARAMETER_IN_VIN,
  ERROR_IN_USER_UPDATE,
  ERROR_USER_TYPE_EXIST,
  USER_BLOCKED,
  ERROR_PARENT_NOT_FOUND,
  AGENT_CREATED,
  AGENT_DELETED,
  ERROR_USER_EXIST,
  UPLOADED_IMAGE,
  ERROR_WRONG_UPDATED_FIELDS,
  DRIVER_LISTED,
  DRIVER_FOUNDED,
  ERROR_UPLOAD_FAILD,
  USER_BLOCK_FOR_INCOMPLETE,
  ERROR_AGENT_CODE_DUPLICATE,
  ERROR_TRANSACTION_NOT_FOUND,
  OPERATOR_DELTED,
  ERROR_UPDATE_USER_TO_ADMIN_OPERTATOR,
  USER_TOKEN_AUTHENTICATE,
  PASSENGER_DELETED,
  ERROR_WRONG_FINANCIAL_INFORMATION,
  USER_GET_INFORMATION,
  ERROR_WRONG_ADDRESS,
  ERROR_SUPER_AGENT_EXIST,
  USER_BLOCK_DRIVER_FOR_WAITING_FOR_CONFIRMATION,
  USER_BLOCK_BY_ADMIN,
  ERROR_SUPER_AGENT_CODE_DUPLICATE,
  USER_UNBLOCK_BY_ADMIN,
  ERROR_USER_USE_IN_OTHER_USER,
  DRIVER_DELETED,
  ERROR_AGENT_ID_AND_DRIVER_ID_NOT_MACH,
  SUPER_AGENT_LISTED,
  VERIFY_CODE_SENT,
  USER_NOT_FOUND,
  PASSENGER_LISTED,
  ERROR_STATUS_UNDEFINED,
  USER_CREATED,
  REQUEST_OK,
  ERROR_SUPER_AGENT_NOT_FOUND,
  USER_UPDATED,
  USER_UPDATED_TO_SUPER_AGENT,
  WALLET_UPDATED,
  AUTH_FAILED,
  ERROR_DRIVER_EXIST,
  ERROR_INTERNAL,
  ERROR_PARAM,
  ERROR_NOT_A_NUMBER,
  ERROR_INVALID_PHONE_NUMBER,
  ERROR_SMS_NOT_SEND,
  ERROR_INVALID_VERIFY_NUMBER,
  USER_BLOCK_AGENT_FOR_WAITING_FOR_CONFIRMATION,
  ERROR_TOO_MANY_ATTEMPT,
  ERROR_INVALID_ID,
  ERROR_TOKEN,
  ERROR_TYPE_NOT_MACH,
  ERROR_REDIS,
  ERROR_GENDER,
  ERROR_AGENT_NOT_FOUND,
  ERROR_AGENT_EXIST,
  ERROR_FULL_NAME_MUST_STRING,
  ERROR_WRONG_PARAMETER,
  ERROR_UPDATE_USER_TO_AGENT,
  ERROR_INSUFFICIENT_BALANCE,
  PASSENGER_FOUNDED,
  ERROR_AMOUNT_MUST_BE_LARGER_THAN_ZERO,
  SUPER_AGENT_CREATED,
  ERROR_USER_TYPE_NOT_PERMITTED,
  ERROR_ADMIN_OPERATOR_EXIST,
}
