const TOKEN = "TOKEN";
const INFO = "INFO";
const USER_TYPE = "USER_TYPE";
const USER_ID = "USER_ID";
const USER_COORDINATES_LATITUDE = "USER_COORDINATES_LATITUDE";
const USER_COORDINATES_LONGITUDE = "USER_COORDINATES_LONGITUDE";
const constants = {
  USER_COORDINATES_LATITUDE,
  USER_COORDINATES_LONGITUDE,
  TOKEN,
  INFO,
  USER_TYPE,
  USER_ID,
};

export default constants;
